version: "3.8"
services:
  ros2_dimi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sofianou_container
    hostname: assessment_container
    tty: true
    stdin_open: true  # in order to use interactive shell
    working_dir: /ros2_ws
    environment:
      - DISPLAY=${DISPLAY}                # allow GUI apps to use host display
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=${XAUTHORITY:-$HOME/.Xauthority}
    volumes:
      - ./src:/ros2_ws/src:rw
      # persist colcon artifacts (speedy rebuilds)
      - ./.colcon/build:/ros2_ws/build:rw
      - ./.colcon/install:/ros2_ws/install:rw
      - ./.colcon/log:/ros2_ws/log:rw
      # X11 socket + auth so RViz can open windows on host
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority:rw
    command: bash