geometry_msgs/Vector3[] a       # M rows of A 
geometry_msgs/Vector3   b       # 3x1 vector b

---
geometry_msgs/Vector3   x_solution    
geometry_msgs/Vector3   x_transform   
float64[9]              r_transform   
geometry_msgs/Vector3   d_transform   
